apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-populated
      app.kubernetes.io/component: mysql-populated
      app.kubernetes.io/instance: mysql-populated
    name: mysql-populated
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-populated
      app.kubernetes.io/component: mysql-populated
      app.kubernetes.io/instance: mysql-populated
    name: mysql-populated
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mysql-populated:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: extend-image
      git:
        uri: https://github.com/sclorg/mysql-container.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: mysql:8.0
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: HiPNKWLuvWKKf6gRu_He
      type: GitHub
    - generic:
        secret: 5SO9GJoxgsVC5kn0p9MM
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"mysql-populated:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"mysql-populated\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-populated
      app.kubernetes.io/component: mysql-populated
      app.kubernetes.io/instance: mysql-populated
    name: mysql-populated
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: mysql-populated
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: mysql-populated
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: sampledb
          - name: MYSQL_PASSWORD
            value: redhat
          - name: MYSQL_USER
            value: redhat
          image: ' '
          name: mysql-populated
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-populated
      app.kubernetes.io/component: mysql-populated
      app.kubernetes.io/instance: mysql-populated
    name: mysql-populated
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      deployment: mysql-populated
  status:
    loadBalancer: {}
kind: List
metadata: {}
