# To get ami id: oc -n openshift-machine-api -o jsonpath='{.spec.template.spec.providerSpec.value.ami.id}{"\n"}' get machineset/<infrastructureID>-worker-us-east-2a

apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: clustername-abcde 
  name: clustername-abcde-worker-us-east-2a-big
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: clustername-abcde 
      machine.openshift.io/cluster-api-machineset: clustername-abcde-worker-us-east-2a-big 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: clustername-abcde 
        machine.openshift.io/cluster-api-machine-role: worker 
        machine.openshift.io/cluster-api-machine-type: worker 
        machine.openshift.io/cluster-api-machineset: clustername-abcde-worker-us-east-2a-big 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: "" 
      taints: 
        - key: node-role.kubernetes.io/worker
          effect: NoSchedule
      providerSpec:
        value:
          ami:
            id: <get-ami>
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: clustername-abcde-worker-profile 
          instanceType: m4.2xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - clustername-abcde-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - clustername-abcde-private-us-east-2a 
          tags:
            - name: kubernetes.io/cluster/clustername-abcde 
              value: owned
          userDataSecret:
            name: worker-user-data
